# Generated by Django 3.1.1 on 2020-10-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20201010_1253'),
        ('posts', '0004_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='like',
            field=models.ManyToManyField(related_name='likes_given', to='users.Profile'),
        ),
    ]
